spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password : paul2858
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
